# Generated by Django 5.2.14 on 2026-06-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
