# Generated by Django 5.2.14 on 2026-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_passwordresetotp_email_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('personal_email', models.EmailField(db_index=True, max_length=254)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(max_length=100)),
                ('line_manager', models.CharField(max_length=255)),
                ('hod', models.CharField(max_length=255)),
                ('stage', models.CharField(default='manager_review', max_length=50)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('pre_installed_software', models.TextField(blank=True)),
                ('employee_installed_software', models.TextField(blank=True)),
                ('manager_software', models.TextField(blank=True)),
                ('hod_software', models.TextField(blank=True)),
                ('review_requested_by', models.CharField(blank=True, max_length=50)),
                ('review_reason', models.TextField(blank=True)),
                ('revision_count', models.IntegerField(default=0)),
                ('manager_approved_at', models.CharField(blank=True, max_length=50)),
                ('hod_approved_at', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
