# Generated by Django 5.2.14 on 2026-06-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_softwarecatalogitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingrequest',
            name='hod_software',
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='asset_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='hod_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='stop_reason',
            field=models.TextField(blank=True),
        ),
    ]
