# Generated by Django 5.2.14 on 2026-06-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_remove_onboardingrequest_hod_software_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
