# Generated by Django 5.2.14 on 2026-06-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_onboardingrequest_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboardingrequest',
            old_name='employee_number',
            new_name='employee_phone_number',
        ),
    ]
