# Generated by Django 5.2.14 on 2026-06-06 05:50

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_rename_employee_number_onboardingrequest_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, validators=[onboarding.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='asset_code',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='department',
            field=models.CharField(max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='employee_name',
            field=models.CharField(max_length=255, validators=[onboarding.models.validate_employee_name]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='employee_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[onboarding.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='hod',
            field=models.CharField(max_length=255, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='hod_comment',
            field=models.TextField(blank=True, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='line_manager',
            field=models.CharField(max_length=255, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='review_reason',
            field=models.TextField(blank=True, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='review_requested_by',
            field=models.CharField(blank=True, max_length=50, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='stop_reason',
            field=models.TextField(blank=True, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='softwarecatalogitem',
            name='name',
            field=models.CharField(max_length=150, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
