# Generated by Django 5.2.14 on 2026-06-06 06:59

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_userprofile_phone_number_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
