# Generated by Django 5.2.14 on 2026-06-08 04:20

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_userprofile_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[onboarding.models.validate_phone_number]),
        ),
    ]
