# Generated by Django 5.2.14 on 2026-06-08 04:21

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[onboarding.models.validate_phone_number]),
        ),
    ]
