# Generated by Django 5.2.14 on 2026-06-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingrequest',
            name='personal_email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
