# Generated by Django 5.2.14 on 2026-06-08 04:50

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0016_alter_onboardingrequest_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
