# Generated by Django 5.2.14 on 2026-06-09 05:42

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_onboardingrequest_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingrequest',
            name='employee_name',
            field=models.CharField(max_length=50, validators=[onboarding.models.validate_employee_name]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='employee_phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[onboarding.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='hod',
            field=models.CharField(max_length=50, validators=[onboarding.models.validate_employee_name]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='line_manager',
            field=models.CharField(max_length=50, validators=[onboarding.models.validate_employee_name]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[onboarding.models.validate_phone_number]),
        ),
    ]
