# Generated by Django 5.2.14 on 2026-06-09 07:05

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0018_alter_onboardingrequest_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingrequest',
            name='hod_comment',
            field=models.TextField(blank=True, validators=[onboarding.models.validate_comment_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='official_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='review_reason',
            field=models.TextField(blank=True, validators=[onboarding.models.validate_comment_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='stop_reason',
            field=models.TextField(blank=True, validators=[onboarding.models.validate_comment_text]),
        ),
    ]
