# Generated by Django 5.2.14 on 2026-06-11 10:29

import django.db.models.deletion
import onboarding.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0019_alter_onboardingrequest_hod_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='infra_admin_comment',
            field=models.TextField(blank=True, validators=[onboarding.models.validate_comment_text]),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='infra_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_infra_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='laptop_model',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='laptop_processor',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='laptop_ram',
            field=models.CharField(blank=True, max_length=50, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='laptop_storage',
            field=models.CharField(blank=True, max_length=50, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
