# Generated by Django 5.2.14 on 2026-06-11 11:33

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0020_onboardingrequest_infra_admin_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=50, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
