# Generated by Django 5.2.14 on 2026-06-12 05:17

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_onboardingrequest_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='laptop_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='laptop_processor',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_comment_text]),
        ),
    ]
