# Generated by Django 5.2.14 on 2026-06-12 08:51

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0023_onboardingrequest_infra_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=100, unique=True, validators=[onboarding.models.validate_generic_text])),
                ('laptop_model', models.CharField(max_length=100, validators=[onboarding.models.validate_generic_text])),
                ('laptop_processor', models.CharField(max_length=100, validators=[onboarding.models.validate_generic_text])),
                ('laptop_ram', models.CharField(max_length=50, validators=[onboarding.models.validate_generic_text])),
                ('laptop_storage', models.CharField(max_length=50, validators=[onboarding.models.validate_generic_text])),
                ('is_assigned', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Asset Inventory',
                'ordering': ['asset_code'],
            },
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='asset_code',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_asset_code]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, validators=[onboarding.models.validate_employee_code]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='laptop_processor',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
