# Generated by Django 5.2.14 on 2026-06-12 09:34

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0024_assetinventory_alter_onboardingrequest_asset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventory',
            name='laptop_gpu',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='laptop_gpu',
            field=models.CharField(blank=True, max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='asset_code',
            field=models.CharField(max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
