# Generated by Django 5.2.14 on 2026-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0025_assetinventory_laptop_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='infra_software',
            field=models.TextField(blank=True, default=''),
        ),
    ]
