# Generated by Django 5.2.14 on 2026-06-15 05:59

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0026_onboardingrequest_infra_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinventory',
            name='laptop_gpu',
            field=models.CharField(blank=True, default='Integrated Graphics', max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
        migrations.AlterField(
            model_name='onboardingrequest',
            name='laptop_gpu',
            field=models.CharField(blank=True, default='Integrated Graphics', max_length=100, validators=[onboarding.models.validate_generic_text]),
        ),
    ]
