# Generated by Django 5.2.14 on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0028_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='changelog',
            name='request_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelogs', to='onboarding.onboardingrequest'),
        ),
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-timestamp']},
        ),
    ]
