# Generated by Django 5.2.14 on 2026-06-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0029_changelog_denormalized_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='softwarecatalogitem',
            name='unique_software_catalog_item_per_category',
        ),
        migrations.AddField(
            model_name='softwarecatalogitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_items', to='onboarding.department'),
        ),
        migrations.AddConstraint(
            model_name='softwarecatalogitem',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'department'), name='unique_software_catalog_item_per_dept'),
        ),
    ]
