# Generated by Django 5.2.14 on 2026-06-17 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0030_remove_softwarecatalogitem_unique_software_catalog_item_per_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='delete_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
