# Generated by Django 5.2.14 on 2026-06-22 08:44

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0031_onboardingrequest_delete_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[onboarding.models.validate_employee_code]),
        ),
    ]
